// <auto-generated />
namespace AuctionLand.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class BidMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BidMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201405012259110_BidMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
